"""Embedded rebirth-cycle data transcribed from the shared workbook."""

CYCLES = {
    1: [
        ("CB", "PIT", "DRK-1 PROBE"), ("BDX EXPLORER", "2BB", "BAL-CORE"),
        ("A-LT", "B-U4D", "R9"), ("ARG", "B1 SECURITY", "GROUNDMECH"),
        ("B-U4D", "HOV-R", "R9"), ("GROUNDMECH", "ARG", "A-LT"),
        ("BB", "B1 SECURITY", "B-U4D"), ("UTIL-TEC", "LO", "HOV-R"),
        ("GROUNDMECH", "R6", "TRAK-R"), ("LO", "HAUL-R", "STRIKE-ORB"),
        ("AMP WALKER", "B1 HEAVY", "BB9"), ("PROTO-ROLLER", "MONO-WLKR", "MECHA-DROID"),
        ("R7", "CYCLO-GRAV", "B2-RP"), ("OPTI-STRK", "MONO-WLKR", "MECHA-DROID"),
        ("B2-RP", "BB9", "R7"), ("OPTI-STRK", "MONO-WLKR", "PROTO-ROLLER"),
        ("B2-RP", "CYCLO-GRAV", "MECHA-DROID"), ("BB9", "R7", "MONO-WLKR"),
        ("B2-RP", "CYCLO-GRAV", "PROTO-ROLLER"), ("R7", "OPTI-STRK", "MECHA-DROID"),
        ("BB", "ORB-WALKER", "GROUNDMECH"), ("AMP WALKER", "B1 HEAVY", "PROTO-ROLLER"),
        ("OPTI-STRK", "MONO-WLKR", "R7"), ("BB9", "CYCLO-GRAV", "MO-TRAK"),
        ("B2-RP", "IG", "DRFT-R"), ("CYCLENS", "LOADLIFTER", "RIC-1200"),
        ("KX", "TRI-TEK", "SNOW MOUSE"),
    ],
    2: [
        ("MOUSE", "GONK", "ID10"), ("ROLL-R", "NAV-EX", "SENATE HOVERCAM"),
        ("R4", "VECT-ARM", "BDX EXPLORER"), ("2BB", "BAL-CORE", "ORB-WALKER"),
        ("R4", "VECT-ARM", "NAV-EX"), ("GUNRUNNER", "2BB", "BAL-CORE"),
        ("ROLL-R", "BDX EXPLORER", "R2"), ("R4", "B2 SUPER", "GUNRUNNER"),
        ("NAV-EX", "STRIKE-ORB", "AMP WALKER"), ("VECT-ARM", "R2", "B2 SUPER"),
        ("STRIKE-ORB", "B2 HEAVY", "BAL-CORE"), ("ORB-WALKER", "R2", "BB9"),
        ("B2 SUPER", "MECHA-DROID", "PROTO-ROLLER"), ("B2 HEAVY", "B2-RP", "R7"),
        ("STRIKE-ORB", "BB9", "PROTO-ROLLER"), ("B2-RP", "AMP WALKER", "MECHA-DROID"),
        ("OPTI-POD", "R7", "MONO-WLKR"), ("UTIL-TEC", "BB9", "PROTO-ROLLER"),
        ("MECHA-DROID", "R7", "B2-RP"), ("MONO-WLKR", "OPTI-STRK", "CYCLO-GRAV"),
        ("LO", "R6", "HAUL-R"), ("SEN-TRI", "STRIKE-ORB", "PROTO-ROLLER"),
        ("BB9", "CYCLO-GRAV", "B2-RP"), ("OPTI-STRK", "B2-RP", "SNOW MOUSE"),
        ("MONO-WLKR", "TRI-TEK", "RIC-1200"), ("KX", "DRFT-R", "IG"),
        ("LEP", "LOADLIFTER", "MO-TRAK"),
    ],
    3: [
        ("MOUSE", "PIT", "GONK"), ("2BB", "R3", "SENATE HOVERCAM"),
        ("R4", "R5", "R8"), ("R9", "B1 BATTLE", "B1 SECURITY"),
        ("2BB", "R3", "SENATE HOVERCAM"), ("BDX EXPLORER", "R4", "R5"),
        ("R8", "R9", "B1 BATTLE"), ("B1 SECURITY", "R3", "2BB"),
        ("BDX EXPLORER", "R4", "R5"), ("TRAK-R", "GROUNDMECH", "SENATE HOVERCAM"),
        ("B2 HEAVY", "B2 SUPER", "UTIL-TEC"), ("TRAK-R", "GROUNDMECH", "BAL-CORE"),
        ("B2 SUPER", "MECHA-DROID", "PROTO-ROLLER"), ("B2 HEAVY", "B2-RP", "R7"),
        ("STRIKE-ORB", "BB9", "PROTO-ROLLER"), ("AMP WALKER", "B2-RP", "MECHA-DROID"),
        ("OPTI-POD", "R7", "MONO-WLKR"), ("UTIL-TEC", "BB9", "PROTO-ROLLER"),
        ("MECHA-DROID", "R7", "B2-RP"), ("MONO-WLKR", "OPTI-STRK", "CYCLO-GRAV"),
        ("B2 SUPER", "OPTI-POD", "R2"), ("GUNRUNNER", "LNG-SHOT", "B2-RP"),
        ("MONO-WLKR", "MECHA-DROID", "CYCLO-GRAV"), ("BB9", "B2-RP", "RIC"),
        ("PROTO-ROLLER", "LOADLIFTER", "MO-TRAK"), ("LEP", "TRI-TEK", "SNOW MOUSE"),
        ("RIC-1200", "IG", "DRFT-R"),
    ],
    4: [
        ("ID10", "PIT", "DRK-1 PROBE"), ("R3", "2BB", "SENATE HOVERCAM"),
        ("R4", "R5", "R8"), ("R9", "B1 BATTLE", "B1 SECURITY"),
        ("2BB", "R3", "SENATE HOVERCAM"), ("BDX EXPLORER", "R4", "R5"),
        ("R8", "R9", "B1 BATTLE"), ("B1 SECURITY", "R3", "2BB"),
        ("BDX EXPLORER", "R4", "R5"), ("TRAK-R", "GROUNDMECH", "SENATE HOVERCAM"),
        ("B2 HEAVY", "B2 SUPER", "UTIL-TEC"), ("BAL-CORE", "GROUNDMECH", "TRAK-R"),
        ("B2 SUPER", "MECHA-DROID", "PROTO-ROLLER"), ("BAL-CORE", "GROUNDMECH", "TRAK-R"),
        ("B2 HEAVY", "B2 SUPER", "B2-RP"), ("UTIL-TEC", "BB9", "R7"),
        ("OPTI-STRK", "CYCLO-GRAV", "MECHA-DROID"), ("B2-RP", "BB9", "R7"),
        ("MECHA-DROID", "R7", "B2-RP"), ("MONO-WLKR", "OPTI-STRK", "CYCLO-GRAV"),
        ("HAUL-R", "GROUNDMECH", "AMP WALKER"), ("B2 SUPER", "STRIKE-ORB", "GUNRUNNER"),
        ("MONO-WLKR", "CYCLO-GRAV", "B2-RP"), ("MECHA-DROID", "PROTO-ROLLER", "MO-TRAK"),
        ("OPTI-STRK", "TRI-TEK", "DRFT-R"), ("CYCLENS", "LEP", "MO-TRAK"),
        ("RIC-1200", "SNOW MOUSE", "LOADLIFTER"),
    ],
}

