"""Verified rebirth-cycle data shared by the workbook and advisor."""

MAX_REBIRTH = 35
NUM_CYCLES = 5

CYCLES = {
    1: [
        ("PIT", "CB", "DRK-1 PROBE"), ("BDX EXPLORER", "BAL-CORE", "2BB"),
        ("A-LT", "B-U4D", "R9"), ("ARG", "B1 SECURITY", "GROUNDMECH"),
        ("B-U4D", "HOV-R", "R9"), ("GROUNDMECH", "ARG", "A-LT"),
        ("BB", "B1 SECURITY", "B-U4D"), ("UTIL-TEC", "LO", "HOV-R"),
        ("GROUNDMECH", "R6", "TRAK-R"), ("LO", "HAUL-R", "STRIKE-ORB"),
        ("AMP WALKER", "B1 HEAVY", "BB9"), ("PROTO-ROLLER", "MONO-WLKR", "MECHA-DROID"),
        ("R7", "CYCLO-GRAV", "B2-RP"), ("OPTI-STRK", "MONO-WLKR", "MECHA-DROID"),
        ("B2-RP", "BB9", "R7"), ("OPTI-STRK", "MONO-WLKR", "PROTO-ROLLER"),
        ("B2-RP", "CYCLO-GRAV", "MECHA-DROID"), ("BB9", "R7", "MONO-WLKR"),
        ("B2-RP", "CYCLO-GRAV", "PROTO-ROLLER"), ("R7", "OPTI-STRK", "MECHA-DROID"),
        ("BB", "ORB-WALKER", "GROUNDMECH"), ("AMP WALKER", "B1 HEAVY", "PROTO-ROLLER"),
        ("OPTI-STRK", "MONO-WLKR", "R7"), ("BB9", "CYCLO-GRAV", "MO-TRAK"),
        ("B2-RP", "IG", "DRFT-R"), ("CYCLENS", "LOADLIFTER", "RIC-1200"),
        ("KX", "TRI-TEK", "SNOW MOUSE"),
        ("MO-TRAK", "DRFT-R", "PROTO-ROLLER"),
        ("IG", "MONO-WLKR", "MECHA-DROID"),
        ("B2-RP", "CYCLENS", "LOADLIFTER"),
        ("SEN-TRI", "PROTO-ROLLER", "KX"),
        ("ORB-WALKER", "OPTI-POD", "RIC"),
        ("B1 HEAVY", "CYCLO-GRAV", "DRFT-R"),
        ("GROUNDMECH", "BB", "CYCLENS"),
        ("BB9", "IG", "SNOW MOUSE"),
    ],
    2: [
        ("MOUSE", "GONK", "ID10"), ("ROLL-R", "NAV-EX", "SENATE HOVERCAM"),
        ("R4", "VECT-ARM", "BDX EXPLORER"), ("2BB", "BAL-CORE", "ORB-WALKER"),
        ("R4", "VECT-ARM", "NAV-EX"), ("GUNRUNNER", "2BB", "BAL-CORE"),
        ("ROLL-R", "BDX EXPLORER", "R2"), ("R4", "B2 SUPER", "GUNRUNNER"),
        ("NAV-EX", "AMP WALKER", "STRIKE-ORB"), ("VECT-ARM", "R2", "B2 SUPER"),
        ("STRIKE-ORB", "B2 HEAVY", "BAL-CORE"), ("ORB-WALKER", "R2", "BB9"),
        ("B2 SUPER", "MECHA-DROID", "PROTO-ROLLER"), ("B2 HEAVY", "B2-RP", "R7"),
        ("STRIKE-ORB", "BB9", "PROTO-ROLLER"), ("B2-RP", "AMP WALKER", "MECHA-DROID"),
        ("OPTI-POD", "R7", "MONO-WLKR"), ("UTIL-TEC", "BB9", "PROTO-ROLLER"),
        ("MECHA-DROID", "R7", "B2-RP"), ("MONO-WLKR", "OPTI-STRK", "CYCLO-GRAV"),
        ("LO", "R6", "HAUL-R"), ("SEN-TRI", "STRIKE-ORB", "PROTO-ROLLER"),
        ("BB9", "CYCLO-GRAV", "B2-RP"), ("OPTI-STRK", "B2-RP", "SNOW MOUSE"),
        ("MONO-WLKR", "TRI-TEK", "RIC-1200"), ("KX", "DRFT-R", "IG"),
        ("LEP", "LOADLIFTER", "MO-TRAK"),
        ("SNOW MOUSE", "TRI-TEK", "MECHA-DROID"),
        ("RIC", "CYCLO-GRAV", "R7"),
        ("OPTI-STRK", "KX", "DRFT-R"),
        ("B2 SUPER", "B2-RP", "LOADLIFTER"),
        ("GUNRUNNER", "B1 HEAVY", "LEP"),
        ("R2", "OPTI-STRK", "KX"),
        ("R6", "LO", "RIC"),
        ("R7", "DRFT-R", "CYCLENS"),
    ],
    3: [
        ("MOUSE", "PIT", "GONK"), ("2BB", "R3", "SENATE HOVERCAM"),
        ("R4", "R5", "R8"), ("R9", "B1 BATTLE", "B1 SECURITY"),
        ("2BB", "R3", "SENATE HOVERCAM"), ("BDX EXPLORER", "R4", "R5"),
        ("R8", "R9", "B1 BATTLE"), ("B1 SECURITY", "R3", "2BB"),
        ("BDX EXPLORER", "R4", "R5"), ("TRAK-R", "GROUNDMECH", "SENATE HOVERCAM"),
        ("B2 HEAVY", "B2 SUPER", "UTIL-TEC"), ("TRAK-R", "GROUNDMECH", "BAL-CORE"),
        ("B2 SUPER", "MECHA-DROID", "PROTO-ROLLER"), ("B2 HEAVY", "B2-RP", "R7"),
        ("STRIKE-ORB", "BB9", "PROTO-ROLLER"), ("B2-RP", "AMP WALKER", "MECHA-DROID"),
        ("OPTI-POD", "R7", "MONO-WLKR"), ("UTIL-TEC", "BB9", "PROTO-ROLLER"),
        ("MECHA-DROID", "R7", "B2-RP"), ("MONO-WLKR", "OPTI-STRK", "CYCLO-GRAV"),
        ("B2 SUPER", "OPTI-POD", "R2"), ("GUNRUNNER", "LNG-SHOT", "B2-RP"),
        ("MONO-WLKR", "MECHA-DROID", "CYCLO-GRAV"), ("BB9", "B2-RP", "RIC"),
        ("PROTO-ROLLER", "LOADLIFTER", "MO-TRAK"), ("LEP", "TRI-TEK", "SNOW MOUSE"),
        ("RIC-1200", "IG", "DRFT-R"),
        ("RIC", "MO-TRAK", "BB9"),
        ("IG", "MECHA-DROID", "OPTI-STRK"),
        ("R7", "LEP", "DRFT-R"),
        ("RIC-1200", "B2 HEAVY", "MECHA-DROID"),
        ("GROUNDMECH", "BB", "MO-TRAK"),
        ("TRAK-R", "MONO-WLKR", "LOADLIFTER"),
        ("ORB-WALKER", "B2 SUPER", "LEP"),
        ("PROTO-ROLLER", "KX", "RIC"),
    ],
    4: [
        ("ID10", "PIT", "DRK-1 PROBE"), ("2BB", "R3", "SENATE HOVERCAM"),
        ("R4", "R5", "R8"), ("R9", "B1 BATTLE", "B1 SECURITY"),
        ("2BB", "R3", "SENATE HOVERCAM"), ("BDX EXPLORER", "R4", "R5"),
        ("R8", "R9", "B1 BATTLE"), ("B1 SECURITY", "R3", "2BB"),
        ("BDX EXPLORER", "R4", "R5"), ("TRAK-R", "GROUNDMECH", "SENATE HOVERCAM"),
        ("B2 HEAVY", "B2 SUPER", "UTIL-TEC"), ("TRAK-R", "GROUNDMECH", "BAL-CORE"),
        ("B2 SUPER", "MECHA-DROID", "PROTO-ROLLER"), ("BAL-CORE", "GROUNDMECH", "TRAK-R"),
        ("B2 HEAVY", "B2 SUPER", "B2-RP"), ("UTIL-TEC", "BB9", "R7"),
        ("OPTI-STRK", "CYCLO-GRAV", "MECHA-DROID"), ("B2-RP", "BB9", "R7"),
        ("MECHA-DROID", "R7", "B2-RP"), ("MONO-WLKR", "OPTI-STRK", "CYCLO-GRAV"),
        ("AMP WALKER", "GROUNDMECH", "HAUL-R"), ("GUNRUNNER", "STRIKE-ORB", "B2 SUPER"),
        ("MONO-WLKR", "B2-RP", "CYCLO-GRAV"), ("MECHA-DROID", "PROTO-ROLLER", "MO-TRAK"),
        ("OPTI-STRK", "TRI-TEK", "DRFT-R"), ("CYCLENS", "LEP", "MO-TRAK"),
        ("RIC-1200", "SNOW MOUSE", "LOADLIFTER"),
        ("IG", "KX", "OPTI-STRK"),
        ("TRI-TEK", "R7", "BB9"),
        ("MONO-WLKR", "CYCLENS", "IG"),
        ("TRAK-R", "CYCLO-GRAV", "TRI-TEK"),
        ("R2", "R6", "IG"),
        ("B2 HEAVY", "BB9", "RIC-1200"),
        ("STRIKE-ORB", "AMP WALKER", "MO-TRAK"),
        ("B2-RP", "LOADLIFTER", "LEP"),
    ],
    5: [
        ("ID10", "MOUSE", "GONK"), ("2BB", "IMPERIAL PROBE", "ROLL-R"),
        ("R4", "VECT-ARM", "BDX EXPLORER"), ("R9", "B1 BATTLE", "B1 SECURITY"),
        ("BAL-CORE", "R4", "R3"), ("GUNRUNNER", "2BB", "BDX EXPLORER"),
        ("ROLL-R", "R5", "R2"), ("B2 SUPER", "R8", "B1 BATTLE"),
        ("NAV-EX", "STRIKE-ORB", "AMP WALKER"), ("IMPERIAL PROBE", "GROUNDMECH", "TRAK-R"),
        ("B2 HEAVY", "B2 SUPER", "UTIL-TEC"), ("BAL-CORE", "GROUNDMECH", "TRAK-R"),
        ("B2 SUPER", "B2 HEAVY", "R2"), ("GROUNDMECH", "TRAK-R", "UTIL-TEC"),
        ("B2 HEAVY", "B2 SUPER", "B2-RP"), ("BB9", "R7", "PROTO-ROLLER"),
        ("OPTI-STRK", "CYCLO-GRAV", "MECHA-DROID"), ("BB9", "B2-RP", "R7"),
        ("OPTI-STRK", "CYCLO-GRAV", "MECHA-DROID"), ("B2-RP", "BB9", "R7"),
        ("LO", "STRIKE-ORB", "HAUL-R"), ("SEN-TRI", "R6", "GUNRUNNER"),
        ("BB9", "CYCLO-GRAV", "B2-RP"), ("MONO-WLKR", "OPTI-STRK", "MO-TRAK"),
        ("MECHA-DROID", "RIC", "TRI-TEK"), ("CYCLENS", "LEP", "SNOW MOUSE"),
        ("RIC-1200", "IG", "LOADLIFTER"), ("RIC", "MO-TRAK", "BB9"),
        ("IG", "MECHA-DROID", "OPTI-STRK"), ("R7", "LEP", "CYCLENS"),
        ("AMP WALKER", "OPTI-STRK", "SNOW MOUSE"),
        ("LO", "TRAK-R", "DRFT-R"),
        ("UTIL-TEC", "R7", "TRI-TEK"),
        ("HAUL-R", "LNG-SHOT", "IG"),
        ("MECHA-DROID", "RIC-1200", "MO-TRAK"),
    ],
}


def next_cycle(cycle: int) -> int:
    """Return the next rebirth cycle, wrapping cycle 5 back to cycle 1."""
    return (cycle % NUM_CYCLES) + 1


def active_rebirth(cycle: int, completed_rebirth: int) -> tuple[int, int]:
    """Return the cycle and rank the player is currently working toward."""
    if completed_rebirth >= MAX_REBIRTH:
        return next_cycle(cycle), 1
    return cycle, completed_rebirth + 1
